### ISSUE TITLE
ETQ visiteur si je ne filtre pas les projets je souhaite par default voir l'ensemble des projets

### ISSUE THREAD

**Issue by riderx** [WildCodeSchool/laloupe-0218-wildfolio#82]
Quand on arrive sur la page on vois aucun projet c'est un peut triste l'inverse serais plus sympa
<img width="1641" alt="screenshot 2018-07-25 at 10 53 47" src="https://user-images.githubusercontent.com/4084527/43190363-29e6b134-8ff9-11e8-98aa-ff302e051f40.png">

**Comment by AntoinePoree** [comment]
Notre client à voulu qu'aucun projet ne s'affiche quand on arrivait sur la page, je vais communiquer autour de ça avec lui pour savoir ce qui est mieux !
