### ISSUE TITLE
Oublie de password : le bouton n'affiche pas le bon texte

### ISSUE THREAD

**Issue by AnthonyHervy** [WildCodeSchool/laloupe-0218-wildfolio#86]
page : https://ppody.innoveduc.fr/users/password/new

le bouton pour valider affiche un texte qui ne correspond pas : 

"<span class="translation_missing" title="translation missing: fr.users.passwords.new.buttons.common.save">Save</span>"

**Comment by Alex-teyss** [comment]
Ce probléme ne vient pas de notre plateforme, mais d'Odyssey. :)
