### ISSUE TITLE
ETQ utilisateur connecter je souhaite comprendre comment mettre a jour ma photo de profils

### ISSUE THREAD

**Issue by riderx** [WildCodeSchool/laloupe-0218-wildfolio#90]
<img width="288" alt="screenshot 2018-07-25 at 15 22 37" src="https://user-images.githubusercontent.com/4084527/43203498-abceed22-901e-11e8-9ba9-17fac302b7ef.png">
lorsque j'edite mon profil un petit texte sous la photo (ou au survol) qui explique que la photo est récupérer par Github serait top !

**Comment by AntoinePoree** [comment]
#90
