### ISSUE TITLE
ETQ utilisateur je peut ajouter des élèves inexistant a un projet 

### ISSUE THREAD

**Issue by riderx** [WildCodeSchool/laloupe-0218-wildfolio#94]
<img width="1194" alt="screenshot 2018-07-25 at 15 39 53" src="https://user-images.githubusercontent.com/4084527/43204456-25d44872-9021-11e8-9105-39178ab8d61e.png">
il suffit de cliquer sur ajouter un eleve sans en avoir selectionner un, un moteur de recherche n'aurais pas fait de mal sur ce dropdown

**Comment by AntoinePoree** [comment]
Fixed !
